### ISSUE TITLE
Can't push to repo.

### ISSUE THREAD

**Issue by zacharyabresch** [8x8Cloud/ramlbadges#1]
Here's what happened after I cloned and tried to `push`:

```
ramlbadges zacharyabresch$ git push -u
ERROR: Permission to 8x8Cloud/ramlbadges.git denied to zacharyabresch.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Perhaps I should have forked it?

**Comment by DragosIorgulescu** [comment]
@zacharyabresch please check now, you should have proper access rights

**Comment by zacharyabresch** [comment]
Totally working. I _can't_ set a webhook on this repo so I created a sample repo to feed commits to the service. Got Sinatra consuming pushes from there so everything is good. Thanks!
